language: nix
before_script: nix-shell --run 'npm i -g pnpm''
script: nix-shell --run 'pnpm install --network-concurrency 1 && pnpm run build && pnpm run test:integration:test'
git:
  quiet: true
  depth: false
# disable default submodule behaviour
  submodules: false
# replace submodule URIs with HTTPS (public) ones, then clone
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init
  - pushd thirdparty/happ-agent-registration
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init
  - popd
branches:
  only:
  - master
  # :NOTE: pull request builds are on, so this takes care of feature branches
  - /^(release|hotfix)\/.*/
# cache:
#   directories:
#   - "/tmp/holochain/target"
#   yarn: true
#   cargo: true
