version: 2

jobs:
 build:
  docker:
   - image: holochain/holonix:latest
  steps:
   - checkout
   - run:
       name: pnpm setup
       command: nix-shell --run 'npm i -g pnpm'
       no_output_timeout: 30s
   - run: nix-shell --run 'pnpm install && pnpm run build && pnpm run test:integration:test'
