[package]
name = "hc_zome_rea_economic_resource_beef"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "0.0.142"

hc_zome_rea_economic_resource_storage_consts = { path = "../../../../../lib/rea_economic_resource/storage_consts" }
hc_zome_rea_economic_resource_defs = { path = "../../../../../lib/rea_economic_resource/defs" }
hc_zome_rea_economic_resource_lib = { path = "../../../../../lib/rea_economic_resource/lib" }
hc_zome_rea_economic_resource_rpc = { path = "../../../../../lib/rea_economic_resource/rpc" }
hc_zome_rea_economic_resource_storage = { path = "../../../../../lib/rea_economic_resource/storage" }
hc_zome_rea_economic_event_rpc = { path = "../../../../../lib/rea_economic_event/rpc" }
hc_zome_rea_resource_specification_storage_consts = { path = "../../../../../lib/rea_resource_specification/storage_consts" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
